In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame as df
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
titanic = pd.read_csv("train.csv")

In [3]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
imputer_med = SimpleImputer(missing_values=np.nan, strategy='median')
titanic[['Age']] = imputer_med.fit_transform(titanic[['Age']])
imputer_fr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
titanic[['Embarked']] = imputer_fr.fit_transform(titanic[['Embarked']])

In [5]:
print(titanic)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [6]:
x = titanic.iloc[:, [2, 4, 5, 6, 7, -1]].values

print(x)

y = titanic.iloc[:, 1].values

print(y)

[[3 'male' 22.0 1 0 'S']
 [1 'female' 38.0 1 0 'C']
 [3 'female' 26.0 0 0 'S']
 ...
 [3 'female' 28.0 1 2 'S']
 [1 'male' 26.0 0 0 'C']
 [3 'male' 32.0 0 0 'Q']]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 1] = le.fit_transform(x[:, 1])
x[:, 5] = le.fit_transform(x[:, 5])
print(x)

[[3 1 22.0 1 0 2]
 [1 0 38.0 1 0 0]
 [3 0 26.0 0 0 2]
 ...
 [3 0 28.0 1 2 2]
 [1 1 26.0 0 0 0]
 [3 1 32.0 0 0 1]]


In [8]:
sc = StandardScaler()
x = sc.fit_transform(x)
print(x)

[[ 0.82737724  0.73769513 -0.56573646  0.43279337 -0.47367361  0.58595414]
 [-1.56610693 -1.35557354  0.66386103  0.43279337 -0.47367361 -1.9423032 ]
 [ 0.82737724 -1.35557354 -0.25833709 -0.4745452  -0.47367361  0.58595414]
 ...
 [ 0.82737724 -1.35557354 -0.1046374   0.43279337  2.00893337  0.58595414]
 [-1.56610693  0.73769513 -0.25833709 -0.4745452  -0.47367361 -1.9423032 ]
 [ 0.82737724  0.73769513  0.20276197 -0.4745452  -0.47367361 -0.67817453]]


In [9]:
w1 = np.random.rand(6,8)
w2 = np.random.rand(8,2)
reg = 0.003
step_size = 0.003
num_examples = x.shape[0]
print(w1)
print(w2)
print(x.shape)


[[0.02050632 0.80218387 0.13297363 0.34147198 0.83887534 0.03644208
  0.03796123 0.52159788]
 [0.34326031 0.73988469 0.97616656 0.77952861 0.27632359 0.59732462
  0.65039723 0.60275203]
 [0.93232638 0.4183101  0.76622531 0.60498983 0.05575151 0.04899822
  0.92180114 0.65717488]
 [0.34574197 0.7873869  0.27756399 0.41544092 0.83437647 0.69247129
  0.20693145 0.99332156]
 [0.89013455 0.77572104 0.56140158 0.1512122  0.39735349 0.57383597
  0.2353364  0.94507589]
 [0.67098567 0.5988961  0.76220247 0.16918038 0.40058025 0.98512836
  0.64147387 0.62245247]]
[[0.23373471 0.87252512]
 [0.35336177 0.64836719]
 [0.7942359  0.75156509]
 [0.48413544 0.98843139]
 [0.31338913 0.75309218]
 [0.95864106 0.38298816]
 [0.65851128 0.97502025]
 [0.99003096 0.24276832]]
(891, 6)


In [10]:
epoch = 40
for i in range(epoch):
    acc = 0
    for n in range(num_examples):
        h1 = np.maximum(0, np.dot(x[n], w1))
        out = np.dot(h1, w2)
        exp_out = np.exp(out)
        probs = exp_out / np.sum(exp_out)
        dscores = probs
        dscores[y[n]] -= 1
        dscores = np.matrix(dscores)
        h1 = np.matrix(h1)
        dW2 = np.dot(h1.T, dscores)
        dhidden = np.dot(dscores, w2.T)
        dhidden[h1 <= 0] = 0
        inp = np.matrix(x[n])
        dW = np.dot(inp.T, dhidden)
        dW2 += reg * w2
        dW += reg * w1
        w1 += -step_size * dW
        w2 += -step_size * dW2
        if np.argmax(out) == y[n]:
            acc += 1
            accuracy = acc / num_examples
    print("epoch =",i, "acc =", accuracy)

epoch = 0 acc = 0.5847362514029181
epoch = 1 acc = 0.6386083052749719
epoch = 2 acc = 0.6655443322109988
epoch = 3 acc = 0.7037037037037037
epoch = 4 acc = 0.7182940516273849
epoch = 5 acc = 0.7272727272727273
epoch = 6 acc = 0.7407407407407407
epoch = 7 acc = 0.7463524130190797
epoch = 8 acc = 0.7497194163860831
epoch = 9 acc = 0.7530864197530864
epoch = 10 acc = 0.7598204264870931
epoch = 11 acc = 0.7609427609427609
epoch = 12 acc = 0.7665544332210998
epoch = 13 acc = 0.7822671156004489
epoch = 14 acc = 0.792368125701459
epoch = 15 acc = 0.7901234567901234
epoch = 16 acc = 0.7957351290684624
epoch = 17 acc = 0.8002244668911336
epoch = 18 acc = 0.8024691358024691
epoch = 19 acc = 0.8080808080808081
epoch = 20 acc = 0.8080808080808081
epoch = 21 acc = 0.8092031425364759
epoch = 22 acc = 0.8069584736251403
epoch = 23 acc = 0.8069584736251403
epoch = 24 acc = 0.8058361391694725
epoch = 25 acc = 0.8080808080808081
epoch = 26 acc = 0.8114478114478114
epoch = 27 acc = 0.8092031425364759
epo

In [11]:
titanic_test = pd.read_csv("test.csv")
titanic_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [12]:
imputer_med = SimpleImputer(missing_values=np.nan, strategy='median')
titanic_test[['Age']] = imputer_med.fit_transform(titanic_test[['Age']])
imputer_fr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
titanic_test[['Embarked']] = imputer_fr.fit_transform(titanic_test[['Embarked']])

In [13]:
test = titanic_test.iloc[:, [1, 3, 4, 5, 6, -1]].values
print(test)

[[3 'male' 34.5 0 0 'Q']
 [3 'female' 47.0 1 0 'S']
 [2 'male' 62.0 0 0 'Q']
 ...
 [3 'male' 38.5 0 0 'S']
 [3 'male' 27.0 0 0 'S']
 [3 'male' 27.0 1 1 'C']]


In [14]:
test[:, 1] = le.fit_transform(test[:, 1])
test[:, 5] = le.fit_transform(test[:, 5])
print(test)

[[3 1 34.5 0 0 1]
 [3 0 47.0 1 0 2]
 [2 1 62.0 0 0 1]
 ...
 [3 1 38.5 0 0 2]
 [3 1 27.0 0 0 2]
 [3 1 27.0 1 1 0]]


In [15]:
test = sc.fit_transform(test)
n_e = test.shape[0]
print(test)
print(n_e)

[[ 0.87348191  0.75592895  0.38623105 -0.49947002 -0.4002477  -0.47091535]
 [ 0.87348191 -1.32287566  1.37137004  0.61699237 -0.4002477   0.70076689]
 [-0.31581919  0.75592895  2.55353683 -0.49947002 -0.4002477  -0.47091535]
 ...
 [ 0.87348191  0.75592895  0.70147553 -0.49947002 -0.4002477   0.70076689]
 [ 0.87348191  0.75592895 -0.20485235 -0.49947002 -0.4002477   0.70076689]
 [ 0.87348191  0.75592895 -0.20485235  0.61699237  0.61989583 -1.64259759]]
418


In [16]:
pred_list = []
for n in range(n_e):
    h1 = np.maximum(0, np.dot(test[n], w1))
    out = np.dot(h1, w2)
    if np.argmax(out) == 0:
        pred_list.append(0)
    else:
        pred_list.append(1)

In [17]:
print(pred_list)

[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 

In [18]:
data = {
    'PassengerId': range(892, 1310),
    'Survived': pred_list }

df = pd.DataFrame(data)

print(df)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


In [19]:
df.to_csv('Results.csv', mode='a', index=False, header=True)

In [20]:
results = pd.read_csv("Results.csv")
results

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]